include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    always_use_package_imports: error
  exclude:
    - build/**
    - android/**
    - ios/**
    - lib/generated/**

linter:
  rules:
    prefer_single_quotes: true
    always_use_package_imports: true
