name: phone
description: "Trenero is a comprehensive management platform designed to help independent trainers, coaches, and tutors streamline their business operations"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.13.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.3.0
  lottie: ^3.6.1
  slang: ^4.19.2
  slang_flutter: ^4.19.0
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2
  google_sign_in: ^7.2.0
  http: ^1.6.0
  flutter_launcher_icons: ^0.14.4
  dio: ^5.11.1
  retrofit: ^4.10.0
  json_annotation: ^4.12.0
  flutter_riverpod: ^3.4.3
  flutter_secure_storage: ^11.2.0
  fl_chart: ^1.2.0
  package_info_plus: ^10.2.1
  custom_refresh_indicator: ^4.0.2
  shimmer_animation: ^2.2.2+1
  persistent_bottom_nav_bar_v2: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.16.1
  slang_build_runner: ^4.19.0
  swagger_parser: ^1.44.3
  json_serializable: ^6.14.1
  retrofit_generator: ^10.2.11


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/

swagger_parser:
  schema_url: http://localhost:8080/v3/api-docs
  output_directory: lib/generated
