CREATE SCHEMA IF NOT EXISTS users_module;
CREATE SCHEMA IF NOT EXISTS groups_module;
CREATE SCHEMA IF NOT EXISTS students_module;
CREATE SCHEMA IF NOT EXISTS lessons_module;
CREATE SCHEMA IF NOT EXISTS attendance_module;
CREATE SCHEMA IF NOT EXISTS payments_module;
